### ISSUE TITLE
Cannot load /assets/js/fileapi/FileAPI/FileAPI.exif.js

### ISSUE THREAD

**Issue by bagi091** [Pathologic/FastImageTV#1]
Как я понимаю этот плагин устанавливается поверх пакета DocLister, но в нем отсутствует файл  **/assets/js/fileapi/FileAPI/FileAPI.exif.js**

**Comment by Pathologic** [comment]
https://github.com/AgelxNash/DocLister/commit/a7ab551e97ac24b57462408428a8efc73d123d79

**Comment by Pathologic** [comment]
Добавил.
