### ISSUE TITLE
кириллица в названии картинок

### ISSUE THREAD

**Issue by bagi091** [Pathologic/FastImageTV#2]
При сохранении картинок на сервере удаляются кириллические символы из названия. При этом все функционирует нормально, ничего не затирается.

**Comment by Pathologic** [comment]
http://ru.stackoverflow.com/questions/417563/%D0%9F%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D0%B0-%D1%81-pathinfo

**Comment by bagi091** [comment]
А может попробовать сделать, чтобы кириллицу в транслит переводило? 
Готов помочь. В ближайшее время постараюсь прислать pull.

**Comment by Pathologic** [comment]
Так перевод в транслит есть, через $modx->stripAlias. Тут проблема в том, что функция pathinfo не правильно работает, если не настроена локаль.

**Comment by Pathologic** [comment]
Можно сделать плагин на OnManagerPageInit и там вписать setlocale(LC_ALL, 'ru_RU.utf8'), но вообще это на сервере должно быть настроено.
