### ISSUE TITLE
PHP7 FastImageTV\Data::checkUnique

### ISSUE THREAD

**Issue by bagi091** [Pathologic/FastImageTV#3]
Здравствуйте. 
При переходе на PHP7 выскочила ошибка. В методе [checkUnique ](https://github.com/Pathologic/FastImageTV/blob/master/assets/tvs/FastImage/core/data.php#L329)класса [Data](https://github.com/Pathologic/FastImageTV/blob/master/assets/tvs/FastImage/core/data.php#L7) используется один агрумент, при этом метод ничего не выполняет. А в родительском классе MODxAPI, есть аналогичный метод, но с тремя аргументами.

Проблема решается либо удалением пустого метода в FastImageTV\Data, либо добавлением аргументов.

**Comment by Pathologic** [comment]
https://github.com/Pathologic/FastImageTV/commit/b402f13327724f57f2615f566c0d713a07869e15
